plugins:
    psutil:
        executor: host_agent
        source: https://github.com/pawelcodilime/cloudify-psutil-plugin/archive/no-psutil-version.zip
        package_name: cloudify-psutil-plugin
        package_version: '1.0.1'
